meta_product_name: "My Games"
meta_title: "My Games - Le réseau social des gamers !"
meta_description: "Retrouve les jeux préférés de tous tes amis gamers"
meta_image: "https://res.cloudinary.com/dtc2l6l05/image/upload/v1599047278/ogimg/ogimage_k1wqeb.png" # should exist in `app/assets/images/`
twitter_account: "@Julien_Evano"   # required for Twitter Cards
